### ISSUE TITLE
Add RPM signature check

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/yum-tools-prod#3]
https://github.com/freedomofpress/apt-tools-prod/issues/3We should verify the signature in CI, as we do for SecureDrop RPM artifacts:
https://github.com/freedomofpress/securedrop-yum-prod/blob/main/.circleci/config.yml

Companion issue to https://github.com/freedomofpress/apt-tools-prod/issues/3

**Comment by apyrgio** [comment]
We can close this issue, since we have this signature check:

https://github.com/freedomofpress/yum-tools-prod/blob/97aed85442670aa4e91b504631c1f2f0a279b105/.github/workflows/check-packages.yml#L17-L21
