### ISSUE TITLE
Add branch protection rules

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/yum-tools-prod#4]
We should set up branch protection for this repo, which will also allow us to enforce the suggested signature check. I think we can probably mirror the `dangerzone` branch protection config for this repo, which also enforces signed commits.

Companion issue to https://github.com/freedomofpress/apt-tools-prod/issues/4

**Comment by apyrgio** [comment]
The `main` branch is now protected, since it requires a passing CI check (which includes signature and smoke tests), and a review by another person.
